name: artifact
on: push
 
jobs:

  artifact:
    runs-on: ubuntu-latest
    outputs:
        output1: ${{ steps.publish.scriptfile }}
    steps:
      - name: get Code
        uses: actions/checkout@v3
        
      - name: install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
            name: dist-files
            path: dist

      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'scriptfile={}' >> $GITHUB_OUTPUT ';'

      - name: name outputs
        run: echo ${{ steps.outputs.output1 }}



