name: call another workflows
on:   
    push:
        branches:
            - main
            - 'dev-*'
            - dev2
jobs:
  calling_workflow:
    uses: ./.github/workflows/sub_workflow_echos.yml
    with:
        param1: "add new parameter"